theme: jekyll-theme-cayman
 
# Setup
title:        [Learn in 60 seconds]
description: [bite sized learning you can use]
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Tanya Gupta
  url:        http://learnin60seconds.com
  baseurl:    ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown  

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true



