theme: jekyll-theme-cayman
 
# Setup
title:        [Learn in 60 seconds]
description: [bite sized learning you can use]
google_analytics: [UA-54473427-1]
baseurl:      ""
paginate:     1
values:
      layout: single

# About/contact
author:
  name:       Tanya Gupta
  url:        http://learnin60seconds.com
  baseurl:    ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown  

include: ["_pages"]


sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed

